#
# Connections that are used for the Blog crate's ArticleType.
---
storage_writers:
  testing.blog.article::domain_event::event_source::writer:
    class: Dailex\CouchDb\Storage\EventStream\EventStreamAppender
    connection: testing.blog.event_source

storage_readers:
  testing.blog.article::event_stream::event_source::reader:
    class: Dailex\CouchDb\Storage\EventStream\EventStreamReader
    connection: testing.blog.event_source
    settings:
      design_doc: testing-blog-article

  testing.blog.article::domain_event::event_source::reader:
    class: Dailex\CouchDb\Storage\DomainEvent\DomainEventReader
    connection: testing.blog.event_source
    settings:
      design_doc: testing-blog-article

units_of_work:
  testing.blog.article::domain_event::event_source::unit_of_work:
    class: Dailex\Infrastructure\DataAccess\UnitOfWork\UnitOfWork
    event_reader: testing.blog.article::event_stream::event_source::reader
    event_writer: testing.blog.article::domain_event::event_source::writer
    dependencies:
      aggregate_root: Testing\Blog\Article\Domain\Article