storage_adapters:
  testing.blog.article:
    class: Daikon\CouchDb\Storage\CouchDbStorageAdapter
    connector: testing.blog.event_store
    settings:
      design_doc: testing-blog-article

stream_stores:
  testing.blog.article:
    class: Daikon\CouchDb\Storage\CouchDbStreamStore
    storage_adapter: testing.blog.article

units_of_work:
  testing.blog.article:
    class: Dailex\Infrastructure\DataAccess\UnitOfWork\UnitOfWork
    stream_store: testing.blog.article
    aggregate_root: Testing\Blog\Article\Domain\Article