#
# Connections that are used for the Blog crate's ArticleType.
---
persistence_adapters:
  testing.blog.article.commit_stream.event_source:
    class: Dailex\Infrastructure\DataAccess\CouchDb2\CouchDb2PersistenceAdapter
    connection: testing.blog.event_source

units_of_work:
  testing.blog.article.commit_stream.event_source:
    class: Dailex\Infrastructure\DataAccess\UnitOfWork\UnitOfWork
    persistence_adapter: testing.blog.article.commit_stream.event_source
    aggregate_root: Testing\Blog\Article\Domain\Article