storage_adapters:
  testing.blog.article.standard:
    class: Daikon\Elasticsearch5\Storage\Elasticsearch5StorageAdapter
    connector: testing.blog.projection_store.standard
    settings:
      type: testing-blog-article-standard

projectors:
  testing.blog.article.standard:
    class: Daikon\ReadModel\Projector\StandardProjector
    repository: testing.blog.article.standard

repositories:
   testing.blog.article.standard:
     class: Testing\Blog\Article\Repository\Standard\ArticleRepository
     storage_adapter: testing.blog.article.standard