#
# Database configuration for the Blog crate Article resource.
---
storage_adapters:
  testing.blog.article.storage_adapter:
    class: Dailex\Infrastructure\DataAccess\CouchDb2\Storage\CouchDb2StorageAdapter
    connector: testing.blog.event_store
    settings:
      design_doc: testing-blog-article

stream_stores:
  testing.blog.article.stream_store:
    class: Dailex\Infrastructure\DataAccess\CouchDb2\Storage\CouchDb2StreamStore
    storage_adapter: testing.blog.article.storage_adapter

units_of_work:
  testing.blog.article.unit_of_work:
    class: Dailex\Infrastructure\DataAccess\UnitOfWork\UnitOfWork
    stream_store: testing.blog.article.stream_store
    aggregate_root: Testing\Blog\Article\Domain\Article