#
# Dailex crate configurations
#

dlx.testing:
  config_dir: /var/www/vendor/dailex/dlx-testing/config
  template_dir: /var/www/vendor/dailex/dlx-testing/templates
  mount: /

dlx.security:
  config_dir: /var/www/vendor/dailex/dlx-security/config
  template_dir: /var/www/vendor/dailex/dlx-security/templates
  mount: /
  auto_login:
    enabled: true
    firewall: default
    target_path: home
  authenticators:
    dlx.security.form_login_authenticator: Dlx\Security\Authentication\FormLoginAuthenticator
    dlx.security.user_token_authenticator: Dlx\Security\Authentication\UserTokenAuthenticator
  voters:
    - Dlx\Security\Voter\OwnershipVoter
  firewalls:
    default:
      guard:
        authenticators:
          #@todo can we combine the authenticator config here with support for entry_point?
          - dlx.security.form_login_authenticator
          - dlx.security.user_token_authenticator
        entry_point: dlx.security.form_login_authenticator
      logout:
        target_url: /
        logout_path: /logout
        invalidate_session: true
        with_csrf: true
      remember_me:
        key: sxfMdXfZJrgcTQ
        lifetime: 1209000