version: "3.2"
secrets:
  couchdb.json:
    file: ../secrets/default/couchdb.json
  elasticsearch.json:
    file: ../secrets/default/elasticsearch.json
  rabbitmq.json:
    file: ../secrets/default/rabbitmq.json
services:
  proxy:
    image: blacklabelops/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER1SERVER_NAME: ${HOST_NAME}
      SERVER1HTTP_ENABLED: "true"
      SERVER1REVERSE_PROXY_LOCATION1: /
      SERVER1REVERSE_PROXY_PASS1: http://nginx:8000
      SERVER1PROXY_APPLICATION: custom
      SERVER1REVERSE_PROXY_HEADER1FIELD1: X-Forwarded-Host ${HOST_NAME}
      SERVER1REVERSE_PROXY_HEADER1FIELD2: X-Forwarded-Proto ${HOST_SCHEME}
      SERVER1REVERSE_PROXY_HEADER1FIELD3: X-Forwarded-For $$proxy_add_x_forwarded_for

  nginx:
    image: nginx:stable
    command: ["nginx", "-c", "/var/www/var/docker/nginx/conf/nginx.conf", "-g", "daemon off;"]
    ports:
      - "8000:8000"
      - "8001:8001"
    links:
      - php:php

  php:
    image: friendsofhoneybee/php:7.1-fpm
    command: ["php-fpm", "-R", "-y", "/var/www/var/docker/php/conf/php-fpm.d/www.conf"]
    working_dir: /var/www
    ports:
      - "9000:9000"
    links:
      - couchdb:couchdb
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
    secrets:
      - couchdb.json
      - elasticsearch.json
      - rabbitmq.json
    environment:
      - APP_VERSION
      - APP_ENV
      - APP_DEBUG
      - HOST_SCHEME
      - HOST_NAME
      - SECRETS_DIR
      - PHP_INI_SCAN_DIR=var/docker/php/conf/conf.d

  couchdb:
    image: couchdb:1
    ports:
      - "5984:5984"

  elasticsearch:
    image: friendsofhoneybee/elasticsearch:2.4
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: friendsofhoneybee/rabbitmq:3.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS